site_name: Higher Elevation Software Documentation
docs_dir: docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.instant
    - search.highlight
plugins:
  - search
  - awesome-pages
  - tags
nav:
  - Home: index.md
